name: Docker Build & Test

on:
  pull_request:
  push:
    branches: ["main", "codex"]

jobs:
  build-test:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build Docker image
        run: |
          docker build -t mlx-llm-server:ci .

      - name: Run container
        run: |
          docker run -d --name mlx_test -p 9123:9123 mlx-llm-server:ci

      - name: Health check
        run: |
          for i in {1..30}; do
            if curl -fs http://localhost:9123/api/v1/health >/dev/null; then
              echo "Server healthy" && exit 0;
            fi;
            sleep 2;
          done;
          echo "Timed out waiting for health check"; docker logs mlx_test; exit 1

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: mlx-llm-server:ci
          format: table
          exit-code: 1
          ignore-unfixed: true

      - name: Cleanup
        if: always()
        run: |
          docker logs mlx_test || true
          docker stop mlx_test || true
          docker rm mlx_test || true